version: '3.1'

networks:
  
  front:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/30
  
  back:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/28

services:

  db:
    image: "mariadb:latest"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=10.0.1.2
    restart: always
    env_file:
      - ./mail.env
    volumes:
      - "${DATA_PATH:-/srv/mailserver}/db:/var/lib/mysql"
    networks:
      back:
        ipv4_address: 10.0.1.2

  memcached:
    image: "memcached:latest"
    container_name: memcached
    networks:
      back:
        ipv4_address: 10.0.1.3

  opendkim:
    image: opendkim
    build:
      context: ./opendkim
    container_name: opendkim
    volumes:
      - "/dev/log:/dev/log"
      - "${DATA_PATH:-/srv/mailserver}/opendkim:/mailserver/opendkim"
    restart: always
    networks:
      back:
        ipv4_address: 10.0.1.4
  
  dovecot:
    image: "dovecot:latest"
    build:
      context: ./dovecot
    container_name: dovecot
    restart: always
    env_file:
      - ./mail.env
    extra_hosts:
      db_host: 10.0.1.2
      postfix_host: 10.0.1.6
    volumes:
      - "${CERTS_DIR}:${CERTS_DIR}"
      - "${DATA_PATH:-/srv/mailserver}/dovecot:/mailserver/do vecot"
      - "${MAILDIR_PATH:-/srv/mailserver/maildir}:/var/mail/vhosts"
    ports:
      - "143:143"
      - "993:993"
    networks:
      back:
        ipv4_address: 10.0.1.5
    depends_on:
      - "db"

  postfix:
    image: "postfix:latest"
    build:
      context: ./postfix
    container_name: postfix
    restart: always
    env_file:
      - ./mail.env
    extra_hosts:
      db_host: 10.0.1.2
      opendkim_host: 10.0.1.4
      dovecot_host: 10.0.1.5
    volumes:
      - "/dev/log:/dev/log"
      - "${CERTS_DIR}:${CERTS_DIR}"
      - "${DATA_PATH:-/srv/mailserver}/postfix:/mailserver/postfix"
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    networks:
      back:
        ipv4_address: 10.0.1.6
    depends_on:
      - "db"
    
  vimbadmin:
    image: "vimbadmin:latest"
    build:
      context: ./vimbadmin
    container_name: vimbadmin
    restart: always
    env_file:
      - ./mail.env
    extra_hosts:
      db_host: 10.0.1.2
      memcached_host: 10.0.1.3
      dovecot_host: 10.0.1.5
      postfix_host: 10.0.1.6
    volumes:
      - "${CERTS_DIR}:${CERTS_DIR}"
      - "${DATA_PATH:-/srv/mailserver}/vimbadmin:/mailserver/vimbadmin"
    networks:
      front:
        ipv4_address: 10.0.0.2
      back:
        ipv4_address: 10.0.1.7
    depends_on:
      - "db"
    