#!/bin/bash

# Tags
info="\e[1m\e[36m[INFO]\e[36m\e[0m"
warn="\e[1m\e[33m[WARN]\e[33m\e[0m"
fatal="\e[1m\e[31m[FATAL]\e[31m\e[0m"
success="\e[1m\e[92m[SUCCESS]\e[92m\e[0m"
ok="\e[1m\e[32m[OK]\e[32m\e[0m"
ko="\e[1m\e[91m[KO]\e[91m\e[0m"

# Globar vars
arg1=$1
arg2=$2
chainable_args=("-c" "-nu" )
data_path="/srv/mailserver"
clean=0
unset_env=1
show_help=0
basic_env_file_docker="basic.env"
advanced_env_file_docker="advanced.env"
mail_env_file_bash="mail.env.bash"
mail_env_file_docker="mail.env"
env_vars=""

# Script

## Functions

function display_help {
    echo "Usage: setup-conf [OPTIONS]"
    echo "[OPTIONS]"
    echo -e "\t--data-path, -d\t| Set the folder where all config files will be placed (default is /srv/mailserver)."
    echo -e "\t--clean, -c\t| Remove original .dist folders and files after setup."
    echo -e "\t--no-unset, -nu\t| Do not unset environmental variables after setup."
    echo -e "\t--help, -h\t| Display this help and exit."
}

function array_contains { 
    local array="$1[@]"
    local seeking=$2
    local in=0
    for element in "${!array}"; do
        if [[ $element == "$seeking" ]]; then
            in=1
            break
        fi
    done
    echo $in
}

function is_chainable {
    result=$(array_contains chainable_args $1)
    echo $result
}

function check_arg {
    arg=$1
    if [[ "$arg" == "-c" ]]; then
        clean=1
    elif [[ "$arg" == "-nu" ]]; then
        unset_env=0
    elif [[ "$arg" == "-h" ]]; then
        show_help=1
    else
        echo -e "$fatal Invalid argument: $arg."
        display_help
        exit 1
    fi
}

function to_short_arg {
    pos=$1
    arg=$2
    if [[ "$arg" == "-c" ]] || [[ "$arg" == "-nu" ]] || [[ "$arg" == "-h" ]]; then
        return
    fi
    if [[ "$arg" == "--clean" ]]; then
        val="-c"
    elif [[ "$arg" == "--no-unset" ]]; then
        val="-nu"
    elif [[ "$arg" == "--help" ]]; then
        val="-h"
    else
        echo -e "$fatal Invalid argument: $arg."
        display_help
        exit 1
    fi

    if [[ "$pos" -eq 1 ]]; then
        arg1=$val
    elif [[ "$pos" -eq 2 ]]; then
        arg2=$val
    else
        echo -e "$fatal Internal error."
        exit -1
    fi
}

function check_args {
    if [[ "$#" -gt 2 ]]; then
        echo -e "$fatal Too many args."
        display_help
        exit 1
    fi
    if [[ "$#" -gt 0 ]]; then
        to_short_arg 1 "$1"
        check_arg "$arg1"
    fi
    if [[ "$#" -gt 1 ]]; then
        to_short_arg 2 "$2"
        if [[ "$1" != "$2" ]] && [[ $(is_chainable "$1") -eq 1 ]] && [[ $(is_chainable "$2") -eq 1 ]]; then
            check_arg "$2"
        else
            echo -e "$fatal Incompatible args: $1 $2"
            display_help
            exit 1
        fi
    fi
    
}

function set_vars {
    echo -en "$info Temporary exporting sensitive data to environment variables..."
    # Ensure tmp env files do not exist
    rm $mail_env_file_bash 2&> /dev/null
    rm $mail_env_file_docker 2&> /dev/null
    # Create tmp env files
    cat $basic_env_file_docker > $mail_env_file_docker
    cat $advanced_env_file_docker >> $mail_env_file_docker
    # Parse docker-friendly env vars and make them bash-friendly
    while IFS='=' read -r name value; do
        if [ -z "$value" -o -z "$name" ]; then
            echo -e "$fatal Unparsable line!"
            exit 1
        fi
        # add quotes around `'`
        value=$(<<<"$value" sed "s/'/'\''/g")
        # set variable with name $name to the value $value
        echo "$name='$value'" >> $mail_env_file_bash 
    done <$mail_env_file_docker
    # Export vars
    export $(xargs <$mail_env_file_bash)
    if [[ "$?" -eq 0 ]]; then
        echo -e " $ok"
    else
        echo -e " $ko"
        echo -e "$fatal Something went wrong. Check .env files."
        exit 1
    fi
}

function fill_config {
    echo -e "$info Filling files with environment data..."
    env_vars=$(grep -v '^#' $mail_env_file_bash | sed -E 's/(.*)=.*/\1/' | xargs)
    readarray -d '' files_to_subst < <(find $data_path/dovecot $data_path/postfix $data_path/vimbadmin $data_path/opendkim -type f -print0)
    for file in "${files_to_subst[@]}"
    do
        echo -en "Replacing all variables of $file..."
        envsubst "$(printf '${%s} ' $env_vars)" < $file > $file.tmp
        if [[ "$?" -eq 0 ]]; then
        mv $file.tmp $file
            echo -e " $ok"
        else
            echo -e " $ko"
            echo -e "$fatal Something went wrong. Check $file."
            exit 1
        fi
    done
}

function unset_vars {
    echo -e "$info Unsetting environment variables..."
    unset $(grep -v '^#' $mail_env_file_bash | sed -E 's/(.*)=.*/\1/' | xargs)
    rm $mail_env_file_bash
    #rm $mail_env_file_docker
}

function clean_resources {
    echo -e "$info Cleaning resources..."
    find ./ -type d -name *.dist | xargs rm -rf
}

function set_dir {
    source="$1/config.dist"
    target="$data_path/$1"
    rm -rf $target 2>/dev/null
    mkdir -p $target
    cp -Rp $source/* $target
    if [[ "$?" -eq 1 ]]; then
        echo -e "$fatal Unable to copy $source into $target!"
        unset_vars
        exit 1
    fi
}

function set_dirs {
    set_dir "dovecot"
    set_dir "opendkim"
    set_dir "postfix"
    set_dir "vimbadmin"
    ### Rename opendkim/config/keys/example.com to keys/example.com
    mv "$data_path/opendkim/keys/example.com" "$data_path/opendkim/keys/example.com"
    fill_config
}

function test_config {
    echo -e "$info Testing configuration..."
    docker-compose config
    if [[ "$?" -ne 0 ]]; then
        echo -e "$fatal Ups, docker-compose configuration does not seem right. Make sure you fill all variables inside basic.env and advanced.env, and don't quote any of them."
        unset_vars
        exit 1
    fi
}

## Permissions check
if [[ "$EUID" -ne 0 ]]; then
   echo -e "$fatal This script must be run as root." 
   exit 1
fi
## Args check
check_args "$@"
if [[ "$show_help" -eq 1 ]]; then
    display_help
    exit 0
fi
## Export env vars
set_vars
## Prepare folder hierarchy
set_dirs
## Test docker-compose configuration
test_config
## Unset ENV vars
if [[ "$unset_env" -eq 1 ]]; then
    unset_vars
fi
## Clean resources
if [[ "$clean" -eq 1 ]]; then
    clean_resources
fi

echo -e "$success All done! Your configuration files are located under $data_path."
exit 0
